version: '3.7'

services:
  postgres_db:
    container_name: task_postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task